version = 5.8.0
archive_dir = /etc/letsencrypt/archive/surat-test.pta-bandung.go.id
cert = /etc/letsencrypt/live/surat-test.pta-bandung.go.id/cert.pem
privkey = /etc/letsencrypt/live/surat-test.pta-bandung.go.id/privkey.pem
chain = /etc/letsencrypt/live/surat-test.pta-bandung.go.id/chain.pem
fullchain = /etc/letsencrypt/live/surat-test.pta-bandung.go.id/fullchain.pem
[renewalparams]
account = 26cb39ea1584f6328f49caad2d2533db
pref_challs = dns-01,
authenticator = manual
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
